server:
  port: 80
  servlet:
    context-path: /activiti/

spring:
  datasource:
    url: jdbc:postgresql://my.dragon.com:5432/activiti
    username: postgres
    password: 123
    driver-class-name: org.postgresql.Driver
  # 添加其他配置信息
  profiles:
    include: activiti
  jpa:
    properties:
      hibernate:
        temp:
          # Spring Boot2需设置
          use_jdbc_metadata_defaults: false
  # security配置
  security:
    user:
      name: user
      password: 123
  devtools:
    restart:
      enabled: true
      additional-paths: src/main/groovy

  # thymeleaf
  thymeleaf:
    prefix: classpath:/templates/
    suffix: .html
    mode: LEGACYHTML5
    encoding: UTF-8
    cache: false
    servlet:
      content-type: text/html
  # 国际化文件
  messages:
    basename: i18n.messages

# mybatis配置
mybatis:
  configuration:
    map-underscore-to-camel-case: true
